# Generated by Django 3.0.2 on 2020-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwrapp', '0003_auto_20180422_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kannada', models.CharField(max_length=50)),
                ('eng', models.CharField(max_length=50)),
                ('mis', models.CharField(max_length=50)),
                ('freq', models.IntegerField()),
                ('comp', models.IntegerField()),
                ('aud', models.FileField(upload_to='audio')),
                ('saud', models.FileField(upload_to='snail_audio')),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
